export enum CurrencyCodes {
  USD = 'USD',
  EUR = 'EUR',
  JPY = 'JPY',
  GBP = 'GBP',
  AUD = 'AUD',
  CAD = 'CAD',
  CHF = 'CHF',
  // not available in table 'a'
  // CNY = 'CNY',
  // HKD = 'HKD',
  // NZD = 'NZD',
  // SEK = 'SEK',
  // KRW = 'KRW',
  // SGD = 'SGD',
  // NOK = 'NOK',
  // MXN = 'MXN',
  // INR = 'INR',
  // RUB = 'RUB',
  // ZAR = 'ZAR',
  // TRY = 'TRY',
  // BRL = 'BRL',
}
